CREATE OR REPLACE TABLE staging.seed_states AS
SELECT * FROM UNNEST([
  STRUCT('CA' AS state_code, 'California' AS state_name),
  STRUCT('TX' AS state_code, 'Texas' AS state_name),
  STRUCT('FL' AS state_code, 'Florida' AS state_name),
  STRUCT('NY' AS state_code, 'New York' AS state_name),
  STRUCT('PA' AS state_code, 'Pennsylvania' AS state_name),
  STRUCT('IL' AS state_code, 'Illinois' AS state_name),
  STRUCT('OH' AS state_code, 'Ohio' AS state_name),
  STRUCT('GA' AS state_code, 'Georgia' AS state_name),
  STRUCT('NC' AS state_code, 'North Carolina' AS state_name),
  STRUCT('MI' AS state_code, 'Michigan' AS state_name),
  STRUCT('NJ' AS state_code, 'New Jersey' AS state_name),
  STRUCT('VA' AS state_code, 'Virginia' AS state_name),
  STRUCT('WA' AS state_code, 'Washington' AS state_name),
  STRUCT('AZ' AS state_code, 'Arizona' AS state_name),
  STRUCT('MA' AS state_code, 'Massachusetts' AS state_name),
  STRUCT('TN' AS state_code, 'Tennessee' AS state_name),
  STRUCT('IN' AS state_code, 'Indiana' AS state_name),
  STRUCT('MD' AS state_code, 'Maryland' AS state_name),
  STRUCT('MO' AS state_code, 'Missouri' AS state_name),
  STRUCT('WI' AS state_code, 'Wisconsin' AS state_name),
  STRUCT('CO' AS state_code, 'Colorado' AS state_name),
  STRUCT('MN' AS state_code, 'Minnesota' AS state_name),
  STRUCT('SC' AS state_code, 'South Carolina' AS state_name),
  STRUCT('AL' AS state_code, 'Alabama' AS state_name),
  STRUCT('LA' AS state_code, 'Louisiana' AS state_name),
  STRUCT('KY' AS state_code, 'Kentucky' AS state_name),
  STRUCT('OR' AS state_code, 'Oregon' AS state_name),
  STRUCT('OK' AS state_code, 'Oklahoma' AS state_name),
  STRUCT('CT' AS state_code, 'Connecticut' AS state_name),
  STRUCT('UT' AS state_code, 'Utah' AS state_name),
  STRUCT('IA' AS state_code, 'Iowa' AS state_name),
  STRUCT('NV' AS state_code, 'Nevada' AS state_name),
  STRUCT('AR' AS state_code, 'Arkansas' AS state_name),
  STRUCT('MS' AS state_code, 'Mississippi' AS state_name),
  STRUCT('KS' AS state_code, 'Kansas' AS state_name),
  STRUCT('NM' AS state_code, 'New Mexico' AS state_name),
  STRUCT('NE' AS state_code, 'Nebraska' AS state_name),
  STRUCT('ID' AS state_code, 'Idaho' AS state_name),
  STRUCT('WV' AS state_code, 'West Virginia' AS state_name),
  STRUCT('HI' AS state_code, 'Hawaii' AS state_name),
  STRUCT('NH' AS state_code, 'New Hampshire' AS state_name),
  STRUCT('ME' AS state_code, 'Maine' AS state_name),
  STRUCT('MT' AS state_code, 'Montana' AS state_name),
  STRUCT('RI' AS state_code, 'Rhode Island' AS state_name),
  STRUCT('DE' AS state_code, 'Delaware' AS state_name),
  STRUCT('SD' AS state_code, 'South Dakota' AS state_name),
  STRUCT('ND' AS state_code, 'North Dakota' AS state_name),
  STRUCT('AK' AS state_code, 'Alaska' AS state_name),
  STRUCT('DC' AS state_code, 'District of Columbia' AS state_name),
  STRUCT('VT' AS state_code, 'Vermont' AS state_name),
  STRUCT('WY' AS state_code, 'Wyoming' AS state_name)
]);